language: c

sudo: false

# Caching so the next build will be fast too.
cache:
  directories:
    - $HOME/.stack

before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

before_install:
  - export PATH=/opt/ghc/7.10.2/bin:$PATH

install:
  - stack -j 2 setup --no-terminal
  - stack -j 2 build --only-snapshot --no-terminal

script:
  - stack -j 2 build --no-terminal

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - ghc-7.10.2
